version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum "requirements/local.txt" }}
          # fallback to using the latest cache if no exact match is found
          - deps-

      - run:
          name: Install dependencies.
          command: make venv

      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements/local.txt" }}

      - run:
          name: Build the site.
          command: |
            . venv/bin/activate
            make build

      - persist_to_workspace:
          root: ryr-docs/
          paths:
            - target/application.jar
            - site/*

  publish:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - attach_workspace:
        at: ryr-docs/

      - add_ssh_keys:
          fingerprints:
            - "0b:0b:0f:19:89:13:94:a8:34:30:b4:13:cb:90:78:25"

      - run:
          name: Deploy the site.
          command: |
            . venv/bin/activate
            cd ryr-docs && mkdocs gh-deploy -v --clean

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
