site_name: Request Yo Racks Documentation
pages:
  - Home: index.md
  - Developer Zone:
    - 'Technical Overview': 'developer-zone/technical-overview.md'
  - About:
    - 'License': 'about/license.md'
