site_name: Request Yo Racks Documentation
pages:
  - Home: index.md
  - Contributor Zone:
    - Goals & Strategy: contributor-zone/goals-strategy.md
    - Technical Overview: 'contributor-zone/technical-overview.md'
  - How-to:
    - Setup full environment: 'how-to/setup-full-environment.md'
  - About:
    - 'License': 'about/license.md'
