site_name: Request Yo Racks Documentation
pages:
  - Home: index.md
  - Contributor Zone:
    - Goals & Strategy: contributor-zone/goals-strategy.md
    - Technical Overview: 'contributor-zone/technical-overview.md'
  - Guides:
    - Setup full environment: 'guides/setup-full-environment.md'
  - About:
    - 'License': 'about/license.md'
theme:
  name: material
  palette:
    primary: green
    accent: lime
  logo:
    icon: directions_bike

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
